-- Kerri Kuhnke

Task 1:
-- ORDERS:
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USER
FOREIGN KEY (USERID)
REFERENCES USERBASE (USERID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_PRODUCT
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST (PRODUCTCODE);

-- REVIEWS:
ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_USER
FOREIGN KEY (USERID)
REFERENCES USERBASE (USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_PRODUCT
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST (PRODUCTCODE);

-- USERLIBRARY:
ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USER
FOREIGN KEY (USERID)
REFERENCES USERBASE (USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_PRODUCT
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTLIST (PRODUCTCODE);

-- Question 2:
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME,
       USERNAME
FROM USERBASE
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, BIRTHDAY) / 12) >= 18;

-- Question 3:
SELECT MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH,
       ROUND(AVG(LENGTH(USERNAME)), 2) AS AVG_USERNAME_LENGTH
FROM USERBASE;

-- Question 4:
SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%'
   OR QUESTION LIKE 'What was%';

-- Question 5:
SELECT PRODUCTCODE,
       MIN(RATING) AS LOWEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;

-- Question 6:
SELECT PRODUCTCODE,
       COUNT(*) AS USER_COUNT
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE
ORDER BY USER_COUNT DESC;

-- Question 7:
SELECT USERID,
       SUM(PRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

-- Question 8:
SELECT PURCHASEDATE,
       SUM(PRICE) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;

-- Question 9:
SELECT *
FROM (
    SELECT PRODUCTCODE,
           SUM(HOURSPLAYED) AS TOTAL_HOURS_PLAYED
    FROM USERLIBRARY
    GROUP BY PRODUCTCODE
    ORDER BY TOTAL_HOURS_PLAYED DESC
)
WHERE ROWNUM <= 5;

-- Question 10:
CREATE VIEW USER_INFRACTION_COUNT_VIEW AS
SELECT USERID,
       COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;

-- Question 11:
CREATE VIEW USER_RULE_INFRACTIONS_VIEW AS
SELECT USERID,
       RULENUM,
       COUNT(*) AS RULE_BREAK_COUNT
FROM INFRACTIONS
GROUP BY USERID, RULENUM;

-- Question 12:
SELECT RULENUM,
       PENALTY,
       COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY
ORDER BY RULENUM;

-- Question 13:
SELECT AVG(DATEUPDATED - DATESUBMITTED) AS AVG_DAYS,
       MAX(DATEUPDATED - DATESUBMITTED) AS MAX_DAYS,
       MIN(DATEUPDATED - DATESUBMITTED) AS MIN_DAYS
FROM USERSUPPORT
WHERE STATUS = 'CLOSED';

-- Question 14:
SELECT EMAIL,
       ISSUE,
       DATESUBMITTED,
       COUNT(*) AS ISSUE_COUNT
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY ISSUE_COUNT DESC;

-- Question 15:
SELECT USERID,
       FIRSTNAME,
       LASTNAME,
       PASSWORD
FROM USERBASE
WHERE UPPER(PASSWORD) LIKE '%' || UPPER(FIRSTNAME) || '%'
   OR UPPER(PASSWORD) LIKE '%' || UPPER(LASTNAME) || '%';

-- Question 16:
SELECT PUBLISHER,
       ROUND(AVG(PRICE), 2) AS AVG_PRICE
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;

-- Question 17:
CREATE VIEW DISCOUNTED_PRODUCTS_VIEW AS
SELECT PRODUCTNAME,
       ROUND(PRICE * 0.75, 2) AS DISCOUNTED_PRICE
FROM PRODUCTLIST
WHERE RELEASEDATE <= ADD_MONTHS(SYSDATE, -60);

-- Question 18:
SELECT GENRE,
       MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCTLIST
GROUP BY GENRE
ORDER BY GENRE;

-- Question 19:
CREATE VIEW RECENT_CHATLOG_VIEW AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE - 7 AND SYSDATE;

-- Question 20:
CREATE VIEW RECENT_INFRACTIONS_VIEW AS
SELECT USERID,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);