-- Kerri Kuhnke

-- 1. Display every USERNAME and the lowest RATING they have left in a review.

SELECT U.USERNAME,
       MIN(R.RATING) AS LOWEST_RATING
FROM USERBASE U
JOIN REVIEWS R
ON U.USERID = R.USERID
GROUP BY U.USERNAME;


-- 2. Display every user's EMAIL, QUESTION, and ANSWER.

SELECT U.EMAIL,
       S.QUESTION,
       S.ANSWER
FROM USERBASE U
JOIN SECURITYQUESTION S
ON U.USERID = S.USERID;


-- 3. Display the FIRSTNAME, EMAIL, and WALLETFUNDS of every user that does not have a WISHLIST.

SELECT U.FIRSTNAME,
       U.EMAIL,
       U.WALLETFUNDS
FROM USERBASE U
WHERE NOT EXISTS (
    SELECT 1
    FROM WISHLIST W
    WHERE W.USERID = U.USERID
);


-- 4. Display every USERNAME and number of products they have ordered.

SELECT U.USERNAME,
       COUNT(*) AS PRODUCTS_ORDERED
FROM USERBASE U
JOIN ORDERS O
ON U.USERID = O.USERID
GROUP BY U.USERNAME;


-- 5. Display the age of any user who has ordered a product within the last 6 months.

SELECT DISTINCT
       FLOOR(MONTHS_BETWEEN(SYSDATE, U.BIRTHDAY)/12) AS AGE
FROM USERBASE U
JOIN ORDERS O
ON U.USERID = O.USERID
WHERE O.PURCHASEDATE >= ADD_MONTHS(SYSDATE,-6);


-- 6. Display the USERNAME and BIRTHDAY of the user who has the highest friend count.

SELECT U.USERNAME,
       U.BIRTHDAY
FROM USERBASE U
JOIN FRIENDSLIST F
ON U.USERID = F.USERID
GROUP BY U.USERID,
         U.USERNAME,
         U.BIRTHDAY
HAVING COUNT(*) = (
    SELECT MAX(FRIEND_COUNT)
    FROM (
        SELECT COUNT(*) AS FRIEND_COUNT
        FROM FRIENDSLIST
        GROUP BY USERID
    )
);


-- 7. Display the PRODUCTNAME, RELEASEDATE, PRICE, and DESCRIPTION for any product found in the WISHLIST table.

SELECT P.PRODUCTNAME,
       P.RELEASEDATE,
       P.PRICE,
       P.DESCRIPTION
FROM PRODUCTLIST P
WHERE EXISTS (
    SELECT 1
    FROM WISHLIST W
    WHERE W.PRODUCTCODE = P.PRODUCTCODE
);


-- 8. Display the PRODUCTNAME, highest RATING, and number of reviews for each product in the REVIEWS table.

SELECT P.PRODUCTNAME,
       MAX(R.RATING) AS HIGHEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM PRODUCTLIST P
JOIN REVIEWS R
ON P.PRODUCTCODE = R.PRODUCTCODE
GROUP BY P.PRODUCTNAME
ORDER BY HIGHEST_RATING DESC;


-- 9. Create a view that displays the PRODUCTNAME, GENRE, and RATING for every product with a 5 or a 1 RATING.

CREATE VIEW PRODUCT_RATINGS_VIEW AS
SELECT P.PRODUCTNAME,
       P.GENRE,
       R.RATING
FROM PRODUCTLIST P
JOIN REVIEWS R
ON P.PRODUCTCODE = R.PRODUCTCODE
WHERE R.RATING IN (1,5)
ORDER BY R.RATING ASC;


-- 10. Display the count of products ordered, grouped by GENRE.

SELECT P.GENRE,
       COUNT(*) AS PRODUCTS_ORDERED
FROM ORDERS O
JOIN PRODUCTLIST P
ON O.PRODUCTCODE = P.PRODUCTCODE
GROUP BY P.GENRE
ORDER BY P.GENRE;


-- 11. Create a view that displays each PUBLISHER, the average PRICE, and the sum of HOURSPLAYED for their products.

CREATE VIEW PUBLISHER_STATS_VIEW AS
SELECT P.PUBLISHER,
       AVG(P.PRICE) AS AVG_PRICE,
       SUM(U.HOURSPLAYED) AS TOTAL_HOURSPLAYED
FROM PRODUCTLIST P
JOIN USERLIBRARY U
ON P.PRODUCTCODE = U.PRODUCTCODE
GROUP BY P.PUBLISHER;


-- 12. Display the sum of money spent on products and their corresponding PUBLISHER.

SELECT P.PUBLISHER,
       SUM(O.PRICE) AS TOTAL_SPENT
FROM ORDERS O
JOIN PRODUCTLIST P
ON O.PRODUCTCODE = P.PRODUCTCODE
GROUP BY P.PUBLISHER
ORDER BY TOTAL_SPENT DESC;


-- 13. Display the TICKETID, USERNAME, EMAIL, and ISSUE only for tickets with a STATUS of 'NEW' or 'IN PROGRESS'.

SELECT T.TICKETID,
       U.USERNAME,
       T.EMAIL,
       T.ISSUE
FROM USERSUPPORT T
JOIN USERBASE U
ON T.EMAIL = U.EMAIL
WHERE T.STATUS IN ('NEW','IN PROGRESS')
ORDER BY T.DATEUPDATED DESC;


-- 14. Display the USERNAME and count of TICKETID that users have submitted for user support.

SELECT U.USERNAME,
       COUNT(T.TICKETID) AS TICKET_COUNT
FROM USERBASE U
JOIN USERSUPPORT T
ON U.EMAIL = T.EMAIL
GROUP BY U.USERNAME;


-- 15. Display the USERID and EMAIL of any user who has submitted a support ticket that used their FIRSTNAME, LASTNAME, or combination of the two in their EMAIL address.

SELECT DISTINCT U.USERID,
       U.EMAIL
FROM USERBASE U
JOIN USERSUPPORT T
ON T.EMAIL = U.EMAIL
WHERE LOWER(T.EMAIL) LIKE '%' || LOWER(U.FIRSTNAME) || '%'
   OR LOWER(T.EMAIL) LIKE '%' || LOWER(U.LASTNAME) || '%'
   OR LOWER(T.EMAIL) LIKE '%' || LOWER(U.FIRSTNAME || U.LASTNAME) || '%';


-- 16. Display the EMAIL address of any user who has a 'NEW' or 'IN PROGRESS' support ticket STATUS, where the EMAIL is not currently saved in USERBASE.

SELECT EMAIL
FROM USERSUPPORT
WHERE STATUS IN ('NEW','IN PROGRESS')
MINUS
SELECT EMAIL
FROM USERBASE;


-- 17. Display the TICKETID, FIRSTNAME, LASTNAME, and USERNAME of any user whose USERNAME is mentioned in the ISSUE of a support ticket.

SELECT T.TICKETID,
       U.FIRSTNAME,
       U.LASTNAME,
       U.USERNAME
FROM USERSUPPORT T
JOIN USERBASE U
ON LOWER(T.ISSUE) LIKE '%' || LOWER(U.USERNAME) || '%';


-- 18. Display the USERNAME and PASSWORD associated with the EMAIL address provided in the support tickets.

SELECT U.USERNAME,
       U.PASSWORD
FROM USERBASE U
JOIN USERSUPPORT T
ON U.EMAIL = T.EMAIL;


-- 19. Create a view that displays the USERNAME, DATEASSIGNED, and PENALTY for any user whose PENALTY is not null and the infraction was assigned within the last month.

CREATE VIEW RECENT_PENALTIES_VIEW AS
SELECT U.USERNAME,
       I.DATEASSIGNED,
       I.PENALTY
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID
WHERE I.PENALTY IS NOT NULL
  AND I.DATEASSIGNED >= ADD_MONTHS(SYSDATE,-1);


-- 20. Display the USERNAME and EMAIL of any user who is at least 18 years old and has not received an infraction within the last 4 months.

SELECT U.USERNAME,
       U.EMAIL
FROM USERBASE U
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE,U.BIRTHDAY)/12) >= 18
AND NOT EXISTS (
    SELECT 1
    FROM INFRACTIONS I
    WHERE I.USERID = U.USERID
      AND I.DATEASSIGNED >= ADD_MONTHS(SYSDATE,-4)
);


-- 21. Display the USERNAME, DATEASSIGNED, and full guideline name.

SELECT U.USERNAME,
       I.DATEASSIGNED,
       C.RULENUM || ' ' || C.TITLE AS GUIDELINE
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID
JOIN COMMUNITYRULES C
ON I.RULENUM = C.RULENUM;


-- 22. Display the USERID, USERNAME, EMAIL, and sum of all SEVERITYPOINT each user has received.

SELECT U.USERID,
       U.USERNAME,
       U.EMAIL,
       SUM(C.SEVERITYPOINT) AS TOTAL_SEVERITY_POINTS
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID
JOIN COMMUNITYRULES C
ON I.RULENUM = C.RULENUM
GROUP BY U.USERID,
         U.USERNAME,
         U.EMAIL;


-- 23. Display the TITLE, DESCRIPTION, and PENALTY for all infractions assigned.

SELECT C.TITLE,
       C.DESCRIPTION,
       I.PENALTY
FROM COMMUNITYRULES C
JOIN INFRACTIONS I
ON C.RULENUM = I.RULENUM;


-- 24. Display the USERNAME and count of infractions for users who have violated the community rules at least 15 times.

SELECT U.USERNAME,
       COUNT(*) AS INFRACTION_COUNT
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID
GROUP BY U.USERNAME
HAVING COUNT(*) >= 15;