-- Kerri Kuhnke
-- Question 1

SELECT USERID
FROM USERBASE

MINUS

SELECT USERID
FROM ORDERS;

-- Question 2

SELECT PRODUCTCODE
FROM PRODUCTLIST

MINUS

SELECT PRODUCTCODE
FROM REVIEWS;

-- Question 3

SELECT U.*,
       CASE
           WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, BIRTHDAY) / 12) >= 18
           THEN 'Adult'
           ELSE 'Minor'
       END AS AGE_GROUP
FROM USERBASE U;

-- Question 4

SELECT P.*,
       CASE
           WHEN PRICE <= 20
           THEN 'On Sale'
           ELSE 'Base Price'
       END AS PRICE_STATUS
FROM PRODUCTLIST P;

-- Question 5

SELECT DISTINCT UL.USERID
FROM USERLIBRARY UL
JOIN USERPROFILE UP
ON UL.USERID = UP.USERID
WHERE UL.PRODUCTCODE = 'GAME6'
AND UP.IMAGEFILE IS NOT NULL;

-- Question 6

SELECT PRODUCTCODE
FROM WISHLIST
WHERE POSITION IN (1,2)

INTERSECT

SELECT PRODUCTCODE
FROM REVIEWS
WHERE RATING >= 3;

-- Question 7

SELECT A.USERNAME,
       A.BIRTHDAY,
       B.USERNAME,
       B.BIRTHDAY
FROM USERBASE A
JOIN USERBASE B
ON A.BIRTHDAY = B.BIRTHDAY
AND A.USERID < B.USERID;

-- Question 8

SELECT *
FROM USERLIBRARY
CROSS JOIN WISHLIST;

-- Question 9

SELECT USERID,
       USERNAME,
       'USER' AS RECORD_TYPE
FROM USERBASE

UNION ALL

SELECT PRODUCTCODE,
       PRODUCTNAME,
       'PRODUCT'
FROM PRODUCTLIST;

-- Question 10

SELECT TO_CHAR(CHATID),
       TO_CHAR(SENDERID),
       'CHATLOG'
FROM CHATLOG

UNION ALL

SELECT TO_CHAR(USERID),
       IMAGEFILE,
       'USERPROFILE'
FROM USERPROFILE;

-- Question 11

SELECT USERNAME
FROM USERBASE

MINUS

SELECT U.USERNAME
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID;

-- Question 12

SELECT TITLE,
       DESCRIPTION
FROM COMMUNITYRULES

MINUS

SELECT C.TITLE,
       C.DESCRIPTION
FROM COMMUNITYRULES C
JOIN INFRACTIONS I
ON C.RULENUM = I.RULENUM;

-- Question 13

SELECT U.USERNAME,
       U.EMAIL
FROM USERBASE U
JOIN INFRACTIONS I
ON U.USERID = I.USERID
WHERE I.PENALTY IS NOT NULL;

-- Question 14

SELECT DATEASSIGNED
FROM INFRACTIONS

INTERSECT

SELECT DATESUBMITTED
FROM USERSUPPORT;

-- Question 15

SELECT C.TITLE,
       I.PENALTY
FROM COMMUNITYRULES C
JOIN INFRACTIONS I
ON C.RULENUM = I.RULENUM;

-- Question 16

SELECT C.*,
       CASE
           WHEN SEVERITYPOINT >= 10
           THEN 'Bannable'
           ELSE 'Appealable'
       END AS RULE_STATUS
FROM COMMUNITYRULES C;

-- Question 17

SELECT U.*,
       CASE
           WHEN STATUS <> 'CLOSED'
            AND DATEUPDATED < SYSDATE - 7
           THEN 'High Priority'
           ELSE ''
       END AS PRIORITY
FROM USERSUPPORT U;

-- Question 18

SELECT *
FROM USERSUPPORT
CROSS JOIN INFRACTIONS;

-- Question 19

SELECT A.TICKETID,
       A.DATEUPDATED,
       B.TICKETID,
       B.DATEUPDATED
FROM USERSUPPORT A
JOIN USERSUPPORT B
ON A.DATEUPDATED = B.DATEUPDATED
AND A.TICKETID < B.TICKETID
WHERE A.STATUS = 'CLOSED'
AND B.STATUS = 'CLOSED';

-- Question 20

SELECT TO_CHAR(USERID),
       USERNAME,
       'USER ACTIVITY'
FROM USERBASE

UNION ALL

SELECT TO_CHAR(USERID),
       PENALTY,
       'INFRACTION ACTIVITY'
FROM INFRACTIONS;